_schema: _schema
paths:
  uploads: src/assets/uploads
  static:
collections_config:
  src_content_episodes:
    path: src/content/episodes
    name: Episodes
    icon: content_paste
    disable_url: false
    description: This is where episodes are managed.
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: src/pages
    name: Pages
    icon: wysiwyg
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: America/Chicago
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: "```"
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
_snippets_imports:
  mdx: true
_snippets:
  premium_video:
    template: mdx_component
    inline: false
    preview:
      text: Premium Video
    definitions:
      component_name: PremiumVideo
      named_args:
        - editor_key: videoUrl
          type: string
    _inputs:
      videoUrl:
        type: url
        label: Video URL
