name = "airwartrail"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-04-22"
compatibility_flags = [ "nodejs_compat" ]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

[vars]
UMAMI_ID = "00000000-0000-0000-0000-000000000000"
TURNSTILE_PUBLIC_KEY = "3x00000000000000000000FF"