name = "airwartrail"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-04-22"
compatibility_flags = [ "nodejs_compat" ]

[assets]
binding = "ASSETS"
directory = "./dist"

[[kv_namespaces]]
binding = "BETTERAUTH_KV"
id = "838df67fbba14d33a8661dfcd40e6058"
preview_id = "37e8db82617b474e960382a848ad6d2e"

[observability]
enabled = true

[vars]
UMAMI_ID = "00000000-0000-0000-0000-000000000000"
TURNSTILE_PUBLIC_KEY = "3x00000000000000000000FF"