name = "airwartrail"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-07-18"
compatibility_flags = [ "nodejs_compat" ]

[assets]
binding = "ASSETS"
directory = "./dist"

[[d1_databases]]
binding = "AIRWARTRAIL_BETTERAUTH_DB"
database_name = "airwartrail-betterauth-prod"
database_id = "4681c0c4-0406-4bde-a0a6-9171789fc995"
preview_database_id = "9db8e957-73c9-4090-9e32-a199cb3b0b7b"
migrations_dir = "./drizzle/migrations"

[[kv_namespaces]]
binding = "AIRWARTRAIL_AUTHSESSIONS_KV"
id = "999bdb40ae474547865ac978cf8bfb56"
preview_id = "ad777aef999948558542184d077a9395"

[observability]
enabled = true

[vars]
BETTER_AUTH_URL = "https://www.airwartrail.com"
UMAMI_ID = "6e001137-4b73-407b-9422-27c1f4bfcb24"
TURNSTILE_PUBLIC_KEY = "3x00000000000000000000FF"